CREATE SCHEMA IF NOT EXISTS analytics;

CREATE TABLE IF NOT EXISTS analytics.flight_operations_enriched (
    icao24                              TEXT NOT NULL,
    callsign                            TEXT,
    origin_country                      TEXT,
    time_position                       INTEGER,
    last_contact                        INTEGER NOT NULL,
    longitude                           NUMERIC,
    latitude                            NUMERIC,
    baro_altitude                       NUMERIC,
    on_ground                           BOOLEAN NOT NULL,
    velocity                            NUMERIC,
    true_track                          NUMERIC,
    vertical_rate                       NUMERIC,
    geo_altitude                        NUMERIC,
    squawk                              TEXT,
    spi                                 BOOLEAN,
    callsign_iata                       TEXT,
    airline_name                        TEXT,
    airline_iata                        TEXT,
    airline_icao                        TEXT,
    dep_airport_iata                    TEXT,
    dep_airport_icao                    TEXT,
    dep_airport_name                    TEXT,
    dep_city                            TEXT,
    dep_country                         TEXT,
    dep_latitude                        NUMERIC,
    dep_longitude                       NUMERIC,
    arr_airport_iata                    TEXT,
    arr_airport_icao                    TEXT,
    arr_airport_name                    TEXT,
    arr_city                            TEXT,
    arr_country                         TEXT,
    arr_latitude                        NUMERIC,
    arr_longitude                       NUMERIC,
    altitude_ft                         NUMERIC,
    velocity_kmh                        NUMERIC,
    flight_direction                    TEXT,
    population_density                  NUMERIC,
    callsign_clean                      TEXT,
    is_in_flight                        BOOLEAN,
    route_distance_km                   NUMERIC,
    is_in_international                 BOOLEAN,
    last_contact_ts                     TIMESTAMPTZ NOT NULL,
    loaded_at                           TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (icao24)
);