CREATE SCHEMA IF NOT EXISTS analytics;

CREATE TABLE IF NOT EXISTS analytics.cible (
    icao24                              TEXT NOT NULL,
    callsign                            TEXT,
    origin_country                      TEXT,
    time_position                       INTEGER,
    last_contact                        INTEGER NOT NULL,
    longitude                           NUMERIC,
    latitude                            NUMERIC,
    baro_altitude                       NUMERIC,
    on_ground                           BOOLEAN NOT NULL,
    velocity                            NUMERIC,
    true_track                          NUMERIC,
    vertical_rate                       NUMERIC,
    geo_altitude                        NUMERIC,
    squawk                              TEXT,
    spi                                 BOOLEAN NOT NULL,
    callsign_iata                       TEXT,
    airline_name                        TEXT,
    airline_iata                        TEXT,
    airline_icao                        TEXT,
    dep_airport_iata                    TEXT,
    dep_airport_icao                    TEXT,
    dep_airport_name                    TEXT,
    dep_city                            TEXT,
    dep_country                         TEXT,
    dep_latitude                        NUMERIC,
    dep_longitude                       NUMERIC,
    arr_airport_iata                    TEXT,
    arr_airport_icao                    TEXT,
    arr_airport_name                    TEXT,
    arr_city                            TEXT,
    arr_country                         TEXT,
    arr_latitude                        NUMERIC,
    arr_longitude                       NUMERIC,
    country_name                        TEXT NOT NULL,
    country_official_name               TEXT,
    country_code                        TEXT NOT NULL,
    region                              TEXT,
    subregion                           TEXT,
    population                          INTEGER,
    area                                NUMERIC,
    capital                             TEXT,
    continent                           TEXT
);